import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:ethesishub/features/forms/form1_data.dart';

const _accent = PdfColor.fromInt(0xFF0B5FA5);
const _green = PdfColor.fromInt(0xFF15803D);

/// A name with clear space above it to sign into. No rule — the spec
/// deliberately leaves the signing area blank.
pw.Widget _signable(String name, String role, {String? status}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 10),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Expanded(
          flex: 58,
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(height: 22),
              pw.Text(name, style: const pw.TextStyle(fontSize: 11.5)),
              pw.Text(role,
                  style: const pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey700)),
            ],
          ),
        ),
        if (status != null)
          pw.Expanded(
            flex: 42,
            child: pw.Text(status,
                textAlign: pw.TextAlign.right,
                style: const pw.TextStyle(fontSize: 9, color: _green)),
          ),
      ],
    ),
  );
}

const _bodyStyle = pw.TextStyle(fontSize: 11);
const _boldNameStyle = pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold);

/// The panel members read as one comma-joined, "and"-terminated sentence
/// fragment — shared by the body paragraph and its bold span so the two can
/// never disagree on wording.
String panelSentence(List<String> panelNames) => panelNames.length <= 1
    ? panelNames.join()
    : '${panelNames.sublist(0, panelNames.length - 1).join(', ')} '
        'and ${panelNames.last}';

/// §7.3: "the printed form's wording, with nominated names in bold." Built
/// as a span tree (rather than a single `pw.Text`) specifically so the
/// adviser's name can carry its own bold style inside an otherwise normal
/// sentence — a plain `pw.Text` cannot mix weights within one string. Kept
/// as a standalone, non-rendering function so a test can inspect the span
/// tree directly without going through `pw.Document`, which loses the
/// weight distinction once the text is packed into the PDF's content
/// stream.
pw.TextSpan buildAdviserParagraphSpan(Form1Data data) {
  final t = data.thesis;
  return pw.TextSpan(style: _bodyStyle, children: [
    pw.TextSpan(
        text: '${data.subjectPronoun} have the honor to nominate Prof./Inst. '),
    pw.TextSpan(
        text: data.adviserName.toUpperCase(), style: _boldNameStyle),
    pw.TextSpan(
        text: ' to be ${data.possessivePronoun} Undergraduate Thesis Adviser '
            'this ${t.semester.toUpperCase()} semester, Academic Year '
            '${t.academicYear}.'),
  ]);
}

/// Same treatment as [buildAdviserParagraphSpan], for the panel members'
/// paragraph.
pw.TextSpan buildPanelParagraphSpan(Form1Data data) {
  return pw.TextSpan(style: _bodyStyle, children: [
    pw.TextSpan(
        text: 'Furthermore, ${data.subjectPronoun.toLowerCase()} '
            '${data.researchers.length > 1 ? "are" : "am"} nominating '
            'Prof./Inst. '),
    pw.TextSpan(
        text: panelSentence(data.panelNames).toUpperCase(),
        style: _boldNameStyle),
    pw.TextSpan(text: ' to be ${data.possessivePronoun} panel members.'),
  ]);
}

/// Generates Form 1 — Nomination of Thesis Adviser and Panel Members — as a
/// PDF. `compress: false` keeps the content streams uncompressed: it costs a
/// little file size, and in exchange the generated bytes stay text-greppable,
/// which is how the tests prove fields actually made it onto the page rather
/// than merely proving the PDF machinery ran.
Future<Uint8List> buildForm1Pdf(Form1Data data) async {
  final doc = pw.Document(compress: false);
  final t = data.thesis;

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(40, 26, 40, 26),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('RD-30-06/24-04',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
          pw.SizedBox(height: 6),
          pw.Center(
            child: pw.Column(children: [
              pw.Text('Republic of the Philippines',
                  style: const pw.TextStyle(fontSize: 10)),
              pw.Text(
                  'ILOILO STATE UNIVERSITY OF FISHERIES SCIENCE AND TECHNOLOGY',
                  textAlign: pw.TextAlign.center,
                  style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: _accent)),
              pw.Text('RESEARCH AND DEVELOPMENT',
                  style: const pw.TextStyle(fontSize: 10)),
              pw.Text('Tiwi, Barotac Nuevo, Iloilo | research@isufst.edu.ph',
                  style: const pw.TextStyle(fontSize: 8.5)),
            ]),
          ),
          pw.SizedBox(height: 5),
          pw.Container(height: 2, color: _accent),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Form 1. Nomination of Thesis Adviser and Panel Members',
                  style: pw.TextStyle(
                      fontSize: 9, fontWeight: pw.FontWeight.bold)),
              pw.Text('Ref. ${t.id.substring(0, t.id.length.clamp(0, 8)).toUpperCase()}',
                  style: const pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey700)),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
                '${data.submittedOn.day} ${_month(data.submittedOn.month)} '
                '${data.submittedOn.year}'),
          ),
          pw.SizedBox(height: 10),
          pw.Text('The Dean'),
          pw.Text('College of ${t.college}'),
          pw.Text('Iloilo State University of Fisheries Science and Technology'),
          pw.Text('Barotac Nuevo, Iloilo'),
          pw.SizedBox(height: 10),
          pw.Text('Sir/Madam:'),
          pw.SizedBox(height: 6),
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 30),
            child: pw.RichText(
              text: buildAdviserParagraphSpan(data),
              textAlign: pw.TextAlign.justify,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 30),
            child: pw.RichText(
              text: buildPanelParagraphSpan(data),
              textAlign: pw.TextAlign.justify,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 30),
            child: pw.Text(
                'Your approval on this matter is highly appreciated.'),
          ),
          pw.SizedBox(height: 12),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('Very truly yours,',
                    style: const pw.TextStyle(fontSize: 11)),
                for (final r in data.researchers) ...[
                  pw.SizedBox(height: 20),
                  pw.Text(r.name.toUpperCase(),
                      style: pw.TextStyle(
                          fontSize: 11.5,
                          fontWeight: r.isLeader
                              ? pw.FontWeight.bold
                              : pw.FontWeight.normal)),
                  pw.Text(
                      r.isLeader ? 'Researcher · Group Leader' : 'Researcher',
                      style: const pw.TextStyle(
                          fontSize: 9, color: PdfColors.grey700)),
                ],
              ],
            ),
          ),
          pw.SizedBox(height: 14),
          pw.Text('Conforme:',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          for (final row in data.conformeRows)
            _signable(row.name, row.role, status: row.status),
          if (data.coordinatorName != null) ...[
            pw.Text('Recommending Approval:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            _signable(data.coordinatorName!, 'College Research Coordinator',
                status: 'Recommended · '
                    '${_stampOf(t.coordinatorRecommendedAt)}'),
          ],
          if (data.deanName != null) ...[
            pw.Text('Approved:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            _signable(data.deanName!, 'Dean, College of ${t.college}',
                status: 'Approved · ${_stampOf(t.deanApprovedAt)}'),
          ],
          pw.SizedBox(height: 6),
          pw.Container(
            padding: const pw.EdgeInsets.all(6),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.blue100),
              color: PdfColors.blue50,
            ),
            child: pw.Text(
              'Electronically completed in eThesisHub. Acceptances recorded '
              'against verified institutional accounts.',
              style: const pw.TextStyle(fontSize: 8),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Integrity  ·  Social Justice  ·  Discipline  ·  Academic Excellence',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    ),
  );

  return doc.save();
}

String _month(int m) => const [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ][m - 1];

String _stampOf(DateTime? d) {
  if (d == null) return '';
  String two(int n) => n.toString().padLeft(2, '0');
  return '${d.day} ${_month(d.month).substring(0, 3)} ${d.year}, '
      '${two(d.hour)}:${two(d.minute)}';
}
