import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:ethesishub/features/forms/form1_data.dart';
import 'package:ethesishub/features/forms/form_chrome.dart';

const _bodyStyle = pw.TextStyle(fontSize: 11);
const _boldNameStyle = pw.TextStyle(
  fontSize: 11,
  fontWeight: pw.FontWeight.bold,
);

/// §7.3: "the printed form's wording, with nominated names in bold." Built
/// as a span tree (rather than a single `pw.Text`) specifically so the
/// adviser's name can carry its own bold style inside an otherwise normal
/// sentence — a plain `pw.Text` cannot mix weights within one string. Kept
/// as a standalone, non-rendering function so a test can inspect the span
/// tree directly without going through `pw.Document`, which loses the
/// weight distinction once the text is packed into the PDF's content
/// stream.
pw.TextSpan buildAdviserParagraphSpan(Form1Data data) {
  final t = data.thesis;
  return pw.TextSpan(
    style: _bodyStyle,
    children: [
      pw.TextSpan(
        text: '${data.subjectPronoun} have the honor to nominate Prof./Inst. ',
      ),
      pw.TextSpan(text: data.adviserName.toUpperCase(), style: _boldNameStyle),
      pw.TextSpan(
        text:
            ' to be ${data.possessivePronoun} Undergraduate Thesis Adviser '
            'this ${t.semester.toUpperCase()} semester, Academic Year '
            '${t.academicYear}.',
      ),
    ],
  );
}

/// Same treatment as [buildAdviserParagraphSpan], for the panel members'
/// paragraph.
pw.TextSpan buildPanelParagraphSpan(Form1Data data) {
  return pw.TextSpan(
    style: _bodyStyle,
    children: [
      pw.TextSpan(
        text:
            'Furthermore, ${data.subjectPronoun.toLowerCase()} '
            '${data.researchers.length > 1 ? "are" : "am"} nominating '
            'Prof./Inst. ',
      ),
      pw.TextSpan(
        text: panelSentence(data.panelNames).toUpperCase(),
        style: _boldNameStyle,
      ),
      pw.TextSpan(text: ' to be ${data.possessivePronoun} panel members.'),
    ],
  );
}

/// Generates Form 1 — Nomination of Thesis Adviser and Panel Members — as a
/// PDF. `compress: false` keeps the content streams uncompressed: it costs a
/// little file size, and in exchange the generated bytes stay text-greppable,
/// which is how the tests prove fields actually made it onto the page rather
/// than merely proving the PDF machinery ran.
Future<Uint8List> buildForm1Pdf(Form1Data data) async {
  final doc = pw.Document(compress: false);
  final t = data.thesis;

  doc.addPage(
    // MultiPage, not Page. `pw.Page` is a fixed single sheet and silently
    // CLIPS whatever does not fit — no exception, no warning, just missing
    // content. A real submission proved it: a group of six researchers with
    // three panel members ran past the bottom of the sheet, and the
    // generated form ended mid-Conforme. The last panel member's row, both
    // ex-officio entries, the Coordinator's "Recommending Approval" block,
    // the Dean's "Approved" block and the page footer were all simply
    // absent — from the document that goes to the Dean for signature.
    //
    // The layout was tuned so a five-researcher group fits one sheet, and it
    // still does. This only changes what happens when a group is larger:
    // the form continues onto a second sheet instead of losing the approval
    // it exists to record.
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(40, 26, 40, 26),
      build: (context) => [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            formChrome(
              rdCode: 'RD-30-06/24-04',
              formTitle:
                  'Form 1. Nomination of Thesis Adviser and Panel Members',
              reference: t.id
                  .substring(0, t.id.length.clamp(0, 8))
                  .toUpperCase(),
            ),
            pw.SizedBox(height: 12),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                '${data.submittedOn.day} ${monthName(data.submittedOn.month)} '
                '${data.submittedOn.year}',
              ),
            ),
            pw.SizedBox(height: 10),
            pw.Text('The Dean'),
            pw.Text('College of ${t.college}'),
            pw.Text(
              'Iloilo State University of Fisheries Science and Technology',
            ),
            pw.Text('Barotac Nuevo, Iloilo'),
            pw.SizedBox(height: 10),
            pw.Text('Sir/Madam:'),
            pw.SizedBox(height: 6),
            pw.Padding(
              padding: const pw.EdgeInsets.only(left: 30),
              child: pw.RichText(
                text: buildAdviserParagraphSpan(data),
                textAlign: pw.TextAlign.justify,
              ),
            ),
            pw.SizedBox(height: 6),
            pw.Padding(
              padding: const pw.EdgeInsets.only(left: 30),
              child: pw.RichText(
                text: buildPanelParagraphSpan(data),
                textAlign: pw.TextAlign.justify,
              ),
            ),
            pw.SizedBox(height: 6),
            pw.Padding(
              padding: const pw.EdgeInsets.only(left: 30),
              child: pw.Text(
                'Your approval on this matter is highly appreciated.',
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    'Very truly yours,',
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                  for (final r in data.researchers) ...[
                    pw.SizedBox(height: 20),
                    pw.Text(
                      r.name.toUpperCase(),
                      style: pw.TextStyle(
                        fontSize: 11.5,
                        fontWeight: r.isLeader
                            ? pw.FontWeight.bold
                            : pw.FontWeight.normal,
                      ),
                    ),
                    pw.Text(
                      r.isLeader ? 'Researcher · Group Leader' : 'Researcher',
                      style: const pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ],
              ),
            ),
            pw.SizedBox(height: 14),
            pw.Text(
              'Conforme:',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            for (final row in data.conformeRows)
              signableLine(row.name, row.role, status: row.status),
            if (data.coordinatorName != null) ...[
              pw.Text(
                'Recommending Approval:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              signableLine(
                data.coordinatorName!,
                'College Research Coordinator',
                status:
                    'Recommended · '
                    '${_stampOf(t.coordinatorRecommendedAt)}',
              ),
            ],
            if (data.deanName != null) ...[
              pw.Text(
                'Approved:',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              signableLine(
                data.deanName!,
                'Dean, College of ${t.college}',
                status: 'Approved · ${_stampOf(t.deanApprovedAt)}',
              ),
            ],
            pw.SizedBox(height: 6),
            pw.Container(
              padding: const pw.EdgeInsets.all(6),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.blue100),
                color: PdfColors.blue50,
              ),
              child: pw.Text(
                'Electronically completed in eThesisHub. Acceptances recorded '
                'against verified institutional accounts.',
                style: const pw.TextStyle(fontSize: 8),
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'Integrity  ·  Social Justice  ·  Discipline  ·  Academic Excellence',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
          ],
        ),
      ],
    ),
  );

  return doc.save();
}

String _stampOf(DateTime? d) {
  if (d == null) return '';
  String two(int n) => n.toString().padLeft(2, '0');
  return '${d.day} ${monthName(d.month).substring(0, 3)} ${d.year}, '
      '${two(d.hour)}:${two(d.minute)}';
}
